language: node_js
node_js:
  - "8"
env:
  CODECLIMATE_REPO_TOKEN: 3923402e82773188cbfd27e2f0ec7d344338097f7582aa6e76246f268165fba5
install:
  - yarn install
before_script:
  - npm install -g codeclimate-test-reporter
script:
  - yarn test
after_success:
  - codeclimate < ./coverage/lcov.info
  